# Generated by Django 4.1.5 on 2023-02-06 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_twitter'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tag_game_name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
