# Generated by Django 4.1.6 on 2023-02-03 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='1', max_length=255),
            preserve_default=False,
        ),
    ]
